package com.zhf.model;

import java.util.Date;

public class UserHealthCardShareRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_health_card_share_record.id
     *
     * @mbg.generated Thu Oct 11 18:44:12 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_health_card_share_record.uid
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_health_card_share_record.card_id
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    private Long cardId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_health_card_share_record.app_name
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_health_card_share_record.greetings
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    private String greetings;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_health_card_share_record.unumber
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    private Long unumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_health_card_share_record.status
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_health_card_share_record.create_time
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_user_health_card_share_record.update_time
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_health_card_share_record.id
     *
     * @return the value of tbl_user_health_card_share_record.id
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_health_card_share_record.id
     *
     * @param id the value for tbl_user_health_card_share_record.id
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_health_card_share_record.uid
     *
     * @return the value of tbl_user_health_card_share_record.uid
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_health_card_share_record.uid
     *
     * @param uid the value for tbl_user_health_card_share_record.uid
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_health_card_share_record.card_id
     *
     * @return the value of tbl_user_health_card_share_record.card_id
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public Long getCardId() {
        return cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_health_card_share_record.card_id
     *
     * @param cardId the value for tbl_user_health_card_share_record.card_id
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_health_card_share_record.app_name
     *
     * @return the value of tbl_user_health_card_share_record.app_name
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public String getAppName() {
        return appName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_health_card_share_record.app_name
     *
     * @param appName the value for tbl_user_health_card_share_record.app_name
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public void setAppName(String appName) {
        this.appName = appName == null ? null : appName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_health_card_share_record.greetings
     *
     * @return the value of tbl_user_health_card_share_record.greetings
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public String getGreetings() {
        return greetings;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_health_card_share_record.greetings
     *
     * @param greetings the value for tbl_user_health_card_share_record.greetings
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public void setGreetings(String greetings) {
        this.greetings = greetings == null ? null : greetings.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_health_card_share_record.unumber
     *
     * @return the value of tbl_user_health_card_share_record.unumber
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public Long getUnumber() {
        return unumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_health_card_share_record.unumber
     *
     * @param unumber the value for tbl_user_health_card_share_record.unumber
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public void setUnumber(Long unumber) {
        this.unumber = unumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_health_card_share_record.status
     *
     * @return the value of tbl_user_health_card_share_record.status
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_health_card_share_record.status
     *
     * @param status the value for tbl_user_health_card_share_record.status
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_health_card_share_record.create_time
     *
     * @return the value of tbl_user_health_card_share_record.create_time
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_health_card_share_record.create_time
     *
     * @param createTime the value for tbl_user_health_card_share_record.create_time
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_user_health_card_share_record.update_time
     *
     * @return the value of tbl_user_health_card_share_record.update_time
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_user_health_card_share_record.update_time
     *
     * @param updateTime the value for tbl_user_health_card_share_record.update_time
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}