package com.zhf.data;

import com.zhf.model.UserHealthCardShareRecord;

public interface UserHealthCardShareRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_health_card_share_record
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_health_card_share_record
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    int insert(UserHealthCardShareRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_health_card_share_record
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    int insertSelective(UserHealthCardShareRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_health_card_share_record
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    UserHealthCardShareRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_health_card_share_record
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    int updateByPrimaryKeySelective(UserHealthCardShareRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user_health_card_share_record
     *
     * @mbg.generated Thu Oct 11 18:44:13 CST 2018
     */
    int updateByPrimaryKey(UserHealthCardShareRecord record);
}